from datetime import datetime
from enum import Enum

from pydantic import EmailStr, Field

from app.models.base import APIModel, Metadata, utc_now


class RecommendationStatus(str, Enum):
    NOT_STARTED = "not_started"
    DRAFTED = "drafted"
    SENT = "sent"
    RECEIVED = "received"


class RecommenderType(str, Enum):
    PROFESSOR = "professor"
    ADVISOR = "advisor"
    MENTOR = "mentor"
    MANAGER = "manager"


DRAFT_REVIEW_BANNER = (
    "[DRAFT FOR RECOMMENDER REVIEW — NOT FOR SUBMISSION]\n"
    "This letter was generated by GrantPilot to assist your recommender. "
    "Please review, personalize, and edit before use.\n"
)


class RecommendationDraft(APIModel):
    id: str
    application_id: str
    recommender_name: str
    recommender_email: EmailStr
    relationship: str
    recommender_type: RecommenderType = RecommenderType.PROFESSOR
    draft_body: str
    version_number: int = Field(default=1, ge=1)
    source_draft_id: str | None = None
    key_talking_points: list[str] = Field(default_factory=list)
    why_it_matches: str = ""
    status: RecommendationStatus = RecommendationStatus.NOT_STARTED
    metadata: Metadata = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)
